package.json, src/App.vue, src/components/CheckboxFilter.vue, src/components/FilterCard.vue, src/components/FilterContainer.vue, src/components/StringFilter.vue, src/components/index.ts, tests/e2e/specs/test.js, tests/unit/StringFilter.spec.ts, tests/unit/__snapshots__/StringFilter.spec.ts.snap, vue.config.js, yarn.lock
=> Use bootstrap-vue, fix e2e tests, upgrade linter

README.md
Based on #5
@fdlk: Let's simply describe what we currently have and not change it at the same time
=> Added initial filter documentation

Jenkinsfile, README.md, package.json
=> [CHORE] Added autorelease

README.md, src/App.vue, src/components/CheckboxFilter.vue, src/components/FilterCard.vue, src/components/StringFilter.vue, tests/e2e/specs/test.js, tests/unit/components/CheckboxFilter.spec.ts, tests/unit/components/FilterCard.spec.ts, tests/unit/components/__snapshots__/CheckboxFilter.spec.ts.snap, tests/unit/components/__snapshots__/FilterCard.spec.ts.snap
Set of changes coming from #5
@connoratrug:
@fdlk:
=> Refactor filter descriptions

Jenkinsfile
set unsave-perm to to to allow CI root user to build/release
=> fix: CI build deploy

package.json
Updated package name to make molgenis-ui-filter part of the @molgenis set
=> choir: updated package name

src/components/AddFilterModal.vue, src/components/FilterCard.vue, src/components/filters/StringFilter.vue, src/main.ts, tests/unit/components/AddFilterModal.spec.ts, tests/unit/components/FilterCard.spec.ts, tests/unit/components/__snapshots__/AddFilterModal.spec.ts.snap, tests/unit/components/__snapshots__/FilterCard.spec.ts.snap, tests/unit/components/filters/StringFilter.spec.ts, tests/unit/components/filters/__snapshots__/StringFilter.spec.ts.snap
Icons will be defined in the component, this makes reusing the objects easier.
=> fix: Move icons to component

src/components/FilterContainer.vue, tests/unit/components/__snapshots__/FilterContainer.spec.ts.snap
Added a show/hide filters button on mobile display
=> Mobile show/hide filter button

README.md
=> Add a missing checkbox property to the docs

README.md, jest.config.js, nightwatch.config.js, package.json, src/App.vue, src/components/FilterContainer.vue, src/components/filters/NumberFilter.vue, src/components/filters/RangeFilter.vue, src/components/filters/index.ts, tests/e2e/specs/test.js, tests/unit/__snapshots__/App.spec.ts.snap, tests/unit/components/filters/NumberFilter.spec.ts, tests/unit/components/filters/RangeFilter.spec.ts, tests/unit/components/filters/StringFilter.spec.ts, tests/unit/components/filters/__snapshots__/NumberFilter.spec.ts.snap, tests/unit/components/filters/__snapshots__/RangeFilter.spec.ts.snap, yarn.lock
=> Add number and range filter

README.md, src/components/filters/NumberFilter.vue, src/components/filters/RangeFilter.vue, tests/unit/components/filters/__snapshots__/NumberFilter.spec.ts.snap, tests/unit/components/filters/__snapshots__/RangeFilter.spec.ts.snap
- No warnings during install
- Updated javascript typing
=> optional slider with range and number filter

README.md, src/App.vue, src/components/ActiveFilters.vue, src/components/filters/CheckboxFilter.vue, src/components/filters/RangeFilter.vue, src/components/index.ts, tests/e2e/specs/test.js, tests/unit/__snapshots__/App.spec.ts.snap, tests/unit/components/ActiveFilters.spec.ts, tests/unit/components/FilterContainer.spec.ts, tests/unit/components/__snapshots__/ActiveFilters.spec.ts.snap, tests/unit/components/__snapshots__/FilterContainer.spec.ts.snap, tests/unit/components/filters/CheckboxFilter.spec.ts, tests/unit/components/filters/RangeFilter.spec.ts, tests/unit/components/filters/__snapshots__/RangeFilter.spec.ts.snap
=> Add active filters

src/components/FilterContainer.vue, tests/unit/components/FilterContainer.spec.ts
=> rewrite listOfVisibleFilters to mirror listOfInvisibleFilters

src/components/ActiveFilters.vue
- User documentation updated
- No warnings during install
- Updated javascript typing
=> fix: activeFilter wil not brake when updated quickly

.npmignore, package.json, tests/unit/components/__snapshots__/FilterContainer.spec.ts.snap, tsconfig.json
=> fix: added the correct parameters

package.json
=> fix: generate lib. files

Jenkinsfile
=> fix: add build step

Jenkinsfile, tests/unit/components/__snapshots__/FilterContainer.spec.ts.snap
=> fix: update snapshot, removed buildstep

src/components/FilterContainer.vue, tests/unit/components/FilterContainer.spec.ts
=> 7245 - Show filters in correct chosen order

package.json, src/components/FilterCard.vue, src/components/FilterContainer.vue, tests/unit/components/__snapshots__/FilterCard.spec.ts.snap, tests/unit/components/__snapshots__/FilterContainer.spec.ts.snap, yarn.lock
=> fix: Make only the cart title listen to drag events

src/components/filters/MultiFilter.vue, tests/unit/components/filters/MultiFilter.spec.ts
=> feat: Multifilter can now populate based on prefilled values.

src/components/FilterContainer.vue
=> fix: remove errors shown when a filter is still loading

src/components/filters/RangeFilter.vue
=> fix: let the range filter react to all user interaction

src/components/ChangeFilters.vue
=> fix: make sure that de add-filter dialog is always reachable

src/components/FilterContainer.vue, src/components/filters/MultiFilter.vue, tests/unit/components/FilterContainer.spec.ts, tests/unit/components/__snapshots__/FilterContainer.spec.ts.snap
=> fix: updated how multifilter reacts, reverted a fix in filtercontainer

README.md
=> fix: jenkins publish to npm

src/App.vue, src/components/filters/RangeFilter.vue, tests/e2e/specs/test.js
1.3 and 1,3 will both be valid numbers now.
=> fix: make the range input react correctly to number that use a dot

README.md
=> feat: release new version
